seed = 10
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "/home/dxlab/data/dxlab/jupyter/seungtae/tabm/SEUNGTAE/korea1.5/dataset"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0003008643713310103
weight_decay = 0.0003585076100054745

[model]
arch_type = "tabm-mini"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 5
d_block = 320
dropout = 0.0
