seed = 2
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "/home/elicer/tabm/SEUNGTAE/korea_base/dataset"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0011563746902507038
weight_decay = 0.0015827100831528388

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 256
dropout = 0.08464895567510722
