seed = 13
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "/home/dxlab/data/dxlab/jupyter/seungtae/tabm/exp/tabm/korea/dataset"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00011184538628817076
weight_decay = 0.0010913099057351175

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 240
dropout = 0.0
