seed = 0
function = "bin.model.main"
n_trials = 100
sampler = { n_startup_trials = 20 }

[space]
seed = 0
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "/home/dxlab/data/dxlab/jupyter/seungtae/tabm/SEUNGTAE/korea_removebuild_mini/dataset"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[space.optimizer]
type = "AdamW"
lr = ["_tune_", "loguniform", 0.0002, 0.002]
weight_decay = ["_tune_", "?loguniform", 0.0, 0.0001, 0.1]


[space.model]
arch_type = "tabm"
k = 32
share_training_batches = false

[space.model.backbone]
type = "MLP"
n_blocks = ["_tune_", "int", 3, 7]
d_block = ["_tune_", "int", 256, 512, 16]
dropout = ["_tune_", "?uniform", 0.0, 0.0, 0.5]
